services:

  mongo_db:
    image: mongo:7.0
    container_name: workshop_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    build: .
    container_name: workshop_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:password123@mongo_db:27017/workshop_db?authSource=admin
    depends_on:
      mongo_db:
        condition: service_healthy
    restart: always

volumes:
  mongo_data: